---
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cppcheck
      - libcaca-dev
      - libsdl1.2-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install cppcheck ncurses sdl ;
    fi
language: c
compiler:
  - clang
  - gcc
sudo: false
script:
  - set -e
  - printenv
  - make
  - make singlethread
  - make omp
  - ls
