---
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cppcheck
      - libcaca-dev
      - libsdl1.2-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install cppcheck ncurses libcaca sdl ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CC" == "gcc" ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc ;
    CC="/usr/local/Cellar/gcc/*/bin/gcc-?" ;
    fi
language: c
compiler:
  - clang
  - gcc
env:
  - TARGET=singlethread
  - TARGET=omp
sudo: false
script:
  - set -e
  - printenv
  - cat /proc/cpuinfo || true
  - make $TARGET
  - ls
matrix:
  fast_finish: true
  allow_failures:
    - compiler: clang
      env: TARGET=omp
